### ISSUE TITLE
Integrate Resizeable & Draggable Dialog Window

### ISSUE THREAD

**Issue by ofilson** [nicholasprussen/cs354-project#6]
Implement the Resizeable & Draggable Dialog Window Javascript show here: 
https://www.cssscript.com/resizable-draggable-dialog/

so that it can be used in the app.

**Comment by nicholasprussen** [comment]
Used JQueryUI, draggability and resizability is now implemented in youtube.js 
9f2e2ed29bf172cc182bf0db606e5e7412a9b93a
