### ISSUE TITLE
Implement an Options page

### ISSUE THREAD

**Issue by ofilson** [nicholasprussen/cs354-project#9]
Put together an options page where you can:

hide certain site connections from the app menu,
change between light mode and dark mode,
the ability to add more options if there is a need.

**Comment by nicholasprussen** [comment]
4c71c9e88ed8ddb831ba868ab7d4b8879cb81947 b3794850afe3f48349085b119d7ef0449c6f7f9a 4b12db9c1826bd733200e4885917976d6ca4da67
